######
# 1. 首先, 在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作
# This is a basic workflow to help you get started with Actions
######

# 工作流名称
name: Sync-K8s-Images-To-DockerHub

run-name: ${{ github.actor }} is Sync Images to DockerHub.

# Controls when the workflow will run
# 怎样触发工作流
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

######
# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job并指定使用的操作系统环境
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
######

# 工作流程任务(通常含有一个或者多个步骤)
jobs:
  syncimages:
    runs-on: ubuntu-latest
    # 在job中添加步骤来执行同步操作, 在上述job中, 添加步骤来执行skopeo命令，从registry.k8s.io仓库拉取镜像，并将其推送到docker.io仓库中
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
    
    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # 设置项目的secrets提供docker hub 登陆
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        ######
        # ingress-nginx 同步
        ######
        # Nginx Ingress Controller 的核心组件
        #skopeo copy --all docker://registry.k8s.io/ingress-nginx/controller:v1.8.4 docker://docker.io/teresajw/ingress-nginx-controller:v1.8.4
        #skopeo copy --all docker://registry.k8s.io/ingress-nginx/controller:v1.9.4 docker://docker.io/teresajw/ingress-nginx-controller:v1.9.4
        skopeo copy --all docker://registry.k8s.io/ingress-nginx/controller:v1.9.6 docker://docker.io/teresajw/ingress-nginx-controller:v1.9.6

        
        # 管理 SSL/TLS 证书
        #skopeo copy --all docker://registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231226-1a7112e06 docker://docker.io/teresajw/ingress-nginx-kube-webhook-certgen:v20231226-1a7112e06
        
        # 后端服务，通常用于处理未匹配到的请求
        #skopeo copy --all docker://registry.k8s.io/defaultbackend-amd64:1.5 docker://docker.io/teresajw/ingress-nginx-defaultbackend-amd64:1.5
        
        # 监控
        #skopeo copy --all docker://registry.k8s.io/metrics-server/metrics-server:v0.7.0 docker://docker.io/teresajw/metrics-server:v0.7.0

        ######
        # k8s 镜像同步
        ######
        # 控制中枢
        #skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.27.4 docker://docker.io/teresajw/kube-apiserver:v1.27.4
        
        # 状态管理器
        #skopeo copy --all docker://registry.k8s.io/kube-controller-manager:v1.27.4 docker://docker.io/teresajw/kube-controller-manager:v1.27.4
        
        # 调度器
        #skopeo copy --all docker://registry.k8s.io/kube-scheduler:v1.27.4 docker://docker.io/teresajw/kube-scheduler:v1.27.4
        
        # 代理负载器
        #skopeo copy --all docker://registry.k8s.io/kube-proxy:v1.27.4 docker://docker.io/teresajw/kube-proxy:v1.27.4
        
        # 基础依赖容器，隔离/共享/通信/生命周期
        #skopeo copy --all docker://registry.k8s.io/pause:3.9 docker://docker.io/teresajw/pause:3.9
        
        # 集群配置数据库
        #skopeo copy --all docker://registry.k8s.io/etcd:3.5.7-0 docker://docker.io/teresajw/etcd:3.5.7-0
        
        # 集群内部Service的解析
        #skopeo copy --all docker://registry.k8s.io/coredns/coredns:v1.10.1 docker://docker.io/teresajw/coredns:v1.10.1

        ######
        # tekton 镜像同步
        ######
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.45.0 docker://teresajw/tektoncd-pipeline-controller:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.45.0 docker://teresajw/tektoncd-pipeline-resolvers:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.45.0 docker://teresajw/tektoncd-pipeline-webhook:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.45.0 docker://teresajw/tektoncd-pipeline-git-init:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.45.0 docker://teresajw/tektoncd-pipeline-entrypoint:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.45.0 docker://teresajw/tektoncd-pipeline-nop:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.45.0 docker://teresajw/tektoncd-pipeline-sidecarlogresults:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.45.0 docker://teresajw/tektoncd-pipeline-imagedigestexporter:v0.45.0
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.45.0 docker://teresajw/tektoncd-pipeline-workingdirinit:v0.45.0
        
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.23.2 docker://teresajw/tektoncd-pipeline-controller:v0.23.2
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.23.2 docker://teresajw/tektoncd-pipeline-webhook:v0.23.2
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.23.2 docker://teresajw/tektoncd-pipeline-interceptors:v0.23.2
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.23.2 docker://teresajw/tektoncd-pipeline-eventlistenersink:v0.23.2
        #skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.35.1 docker://teresajw/tektoncd-pipeline-dashboard:v0.35.1

        
        #skopeo copy --all docker://registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 docker://docker.io/teresajw/nfs-subdir-external-provisioner:v4.0.2
        
        skopeo copy --all docker://registry.k8s.io/dns/k8s-dns-node-cache:1.22.28 docker://docker.io/teresajw/k8s-dns-node-cache:1.22.28
