######
# 1. 首先, 在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作
# This is a basic workflow to help you get started with Actions
######

# 工作流名称
name: Sync-K8s-Images-To-DockerHub

run-name: ${{ github.actor }} is Sync Images to DockerHub.

# Controls when the workflow will run
# 怎样触发工作流
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

######
# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job并指定使用的操作系统环境
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
######

# 工作流程任务(通常含有一个或者多个步骤)
jobs:
  syncimages:
    runs-on: ubuntu-latest
    # 在job中添加步骤来执行同步操作, 在上述job中, 添加步骤来执行skopeo命令，从registry.k8s.io仓库拉取镜像，并将其推送到docker.io仓库中
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
    
    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    # 设置项目的secrets提供docker hub 登陆
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://registry.k8s.io/kube-apiserver:v1.27.4 docker://docker.io/teresajw/kube-apiserver:v1.27.4
        skopeo copy --all docker://registry.k8s.io/kube-controller-manager:v1.27.4 docker://docker.io/teresajw/kube-controller-manager:v1.27.4
        skopeo copy --all docker://registry.k8s.io/kube-scheduler:v1.27.4 docker://docker.io/teresajw/kube-scheduler:v1.27.4
        skopeo copy --all docker://registry.k8s.io/kube-proxy:v1.27.4 docker://docker.io/teresajw/kube-proxy:v1.27.4
        skopeo copy --all docker://registry.k8s.io/pause:3.9 docker://docker.io/teresajw/pause:3.9
        skopeo copy --all docker://registry.k8s.io/etcd:3.5.7-0 docker://docker.io/teresajw/etcd:3.5.7-0
        skopeo copy --all docker://registry.k8s.io/coredns/coredns:v1.10.1 docker://docker.io/teresajw/coredns:v1.10.1
    

